Отрисуй меня полностью (часть 1)
htmlacademy-javascript/393331-keksobooking-22 pull request #5
Opened 2021-02-14 19:37 UTC by alianta

2021-02-15 14:28 UTC, ademaro commented on js/ad-card.js
> +const TYPES = new Map([
Чем не устроил стандартный объект?)

2021-02-15 14:29 UTC, ademaro commented on js/ad-card.js
> +const TYPES = new Map([
В целом — ок, можем оставить, заодно пробуем что-то новое)

2021-02-15 14:29 UTC, ademaro commented on js/ad-card.js
> +adCards.forEach((card)=>{
пробелы до и после стрелки...

2021-02-15 14:31 UTC, ademaro commented on js/ad-card.js
> +  //features - не ясно как это отображать (скрыть неактивные)
фичи уже есть в шаблоне, поэтому:
1. очищать и добавлять в DOM то, что есть в объекте
2. сразу удалять те, которых нет в объекте

2021-02-15 14:31 UTC, ademaro commented on js/ad-card.js
> +  //popup__photos - не ясно как это - Я копировала шиблон img и добавила ещё такие же, но с другими адресами
да, тут всё так)

2021-02-15 14:33 UTC, ademaro commented on js/ad-card.js
> +adCards.forEach((card)=>{
и зачем ты делаешь кучу карточек для всех объявлений. Давай переделаем на именованную функцию показа карточки:
`showCard(adCards[0]);` — сейчас будет так у тебя...

2021-02-15 14:35 UTC, ademaro commented on js/main.js
> +import './ad-card.js';
в ad-card будет функция showCard (или renderCard), например. Мы её импортим. А тут запускаем для того, что сгенерировали.

2021-02-15 14:35 UTC, ademaro commented on js/ad-card.js
> +const adCards = getRandomArrayAdvertisements(RANDOM_AD_CARD_COUNT);
Переносим генерацию обратно в main

2021-02-15 14:35 UTC, ademaro requested changes
Жду поправок

2021-02-17 18:29 UTC, alianta commented on js/main.js
> +import './ad-card.js';
нам же надо ещё при вызове showCard передать ей данные которые ода добавить в карточку, 
т.е. showCard(adCards[0]); 
получается мы всё равно тут сначала должны вызвать функцию генерации данных для карточки, а потом уже передать её результат функции отрисовки карточки:
const adCards = getRandomArrayAdvertisements(RANDOM_OBJECTS_COUNT);
showCard(adCards[0]);
или я что-то неправильно понимаю?

2021-02-19 15:32 UTC, ademaro commented on js/main.js
> +import './ad-card.js';
Всё именно так! Супер, закрываю ПР.

2021-02-19 15:32 UTC, merged